blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
# from register import views as v
# from polls import views as vi


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('blog.urls')),
    # path('polls/', vi.index, name='polls'),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text


def approved_comments(self):
    return self.comments.filter(approved_comment=True)

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='questions', null=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)


# class EmailPostForm(forms.Form):
#     name = forms.CharField(max_length=25)
#     email = forms.EmailField()
#     to = forms.EmailField()
#     comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.template import RequestContext

from .models import Post, Comment
from .forms import PostForm, CommentForm
from utils.utils import is_superuser


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    paginator = Paginator(posts, 10)
    page = request.GET.get('page')
    try:
        postss = paginator.page(page)
    except PageNotAnInteger:
        postss = paginator.page(1)
    except EmptyPage:
        postss = paginator.page(paginator.num_pages)
    vars = dict(
        posts=postss
    )
    return render(request, 'blog/post_list.html', vars)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})



@login_required
@is_superuser
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_new.html', {'form': form})


@login_required
@is_superuser
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
@is_superuser
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


@login_required
@is_superuser
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)


@login_required
@is_superuser
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
@is_superuser
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)


@login_required
@is_superuser
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style type="text/css">
<!--		.sidenav {-->
<!--			height: 90%;-->
<!--			width: 160px;-->
<!--			position: fixed;-->
<!--			z-index:1;-->
<!--			top: 10;-->
<!--			left: 10;-->
<!--			background-color:#D3F67B;-->
<!--			overflow-x: :hidden;-->
<!--			padding-top:40px;-->
<!--		}-->

	    </style>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}?ver=2"/>
        <title>Rogoyx Blog</title>
<!--	    <link href="https://fonts.googleapis.com/css?family=Pacifico&subset=latin,cyrillic" rel="stylesheet" type="text/css">-->
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="{% static 'css/blog-home.css' %}">
         <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- JS code for snow -->
        <script src="{% static 'js/snowfall2020.js' %}"/></script>
    </head>

    <body>

    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">Rogoyx Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/post/new/">New post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/drafts/">Drafts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/polls/">Polls</a>
          </li>
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="/contacts/">Contact me</a>-->
<!--          </li>-->
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">
          <small></small>
        </h1>

        <!-- Blog Posts -->
            {% block content %}
            {% endblock %}


      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">WELCOME!</h5>
          <div class="card-body">
            {% if user.is_authenticated %}
                <p><medium>Hello {{ user.username }}!</medium></p>
                <p><a href="{% url 'logout' %}" class="text-secondary">Logout</a></p>
            {% else %}
                <a href="{% url 'login' %}" class="text-info">Login</a>
                <a href="/register/" class="text-info">Registration</a>
            {% endif %}
          </div>
        </div>

<!--        &lt;!&ndash; Search Widget &ndash;&gt;-->
<!--        <div class="card my-4">-->
<!--          <h5 class="card-header">Search</h5>-->
<!--          <div class="card-body">-->
<!--            <div class="input-group">-->
<!--              <input type="text" class="form-control" placeholder="Search for...">-->
<!--              <span class="input-group-btn">-->
<!--                <button class="btn btn-info" type="button">Go!</button>-->
<!--              </span>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->

<!--        &lt;!&ndash; Categories Widget &ndash;&gt;-->
        <div class="card my-4">
          <h5 class="card-header">WELCOME 2.0</h5>
          <div class="card-body">
            <div class="row">
<!--              <div class="col-lg-6">-->
<!--                <ul class="list-unstyled mb-0">-->
                <p></p>
                <p> <big>Всем привет! Меня зовут Маша и здесь я пишу о дополнительных карточках к настольной игре 74. А ещё пробую делать сайт. </big></p>

                <p></p>
<!--                  <li>-->
<!--                    <a href="#" class="text-info">Web Design</a>-->
<!--                  </li>-->
<!--                  <li>-->
<!--                    <a href="#" class="text-info">HTML</a>-->
<!--                  </li>-->
<!--                  <li>-->
<!--                    <a href="#" class="text-info">Freebies</a>-->
<!--                  </li>-->
<!--                </ul>-->
<!--              </div>-->
<!--              <div class="col-lg-6">-->
<!--                <ul class="list-unstyled mb-0">-->
<!--                  <li>-->
<!--                    <a href="#" class="text-info">JavaScript</a>-->
<!--                  </li>-->
<!--                  <li>-->
<!--                    <a href="#" class="text-info">CSS</a>-->
<!--                  </li>-->
<!--                  <li>-->
<!--                    <a href="#" class="text-info">Tutorials</a>-->
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>



      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->


            </div>
        </div>
    </div>


    <!-- Footer -->
  <footer class="py-5 bg-info" class="footer navbar-fixed-bottom">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Rogoyx Blog 2019-2020</p>
      <div class="m-0 text-center text-info"><a class="text-secondary" href="/#">Back to top</a></div>
    </div>
    <!-- /.container -->
  </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'post_publish' pk=post.pk %}">Publish</a>
        {% endif %}
        <p></p>
        {% if user.is_authenticated %}
            <a class="btn btn-info" href="{% url 'post_edit' pk=post.pk %}">Edit</a>
            <a class="btn btn-info" href="{% url 'post_remove' pk=post.pk %}">Remove</a>
        {% endif %}
        <p></p>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>

        <hr class="m-y-2">
        {% for question in post.questions.all %}
    <p>{{ question.question_text }}</p>
        <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <button type="submit" class="btn btn-info">Vote</button>
    </form>
{% endfor %}
    </div>
    <hr>
    <a class="btn btn-info" href="{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a>
    <p></p>
    {% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-info" href="{% url 'comment_remove' pk=comment.pk %}">Remove</span></a>
                <a class="btn btn-info" href="{% url 'comment_approve' pk=comment.pk %}">Ok</span></a>
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
	{% for post in posts %}
		<div class="card mb-4">
          <div class="card-body">
			  <div class="post">
        		<div class="date">
					<p>{{ post.published_date }}</p>
				</div>
				<h1><a>{{ post.title }}</a></h1>
				<p>{{ post.text|truncatewords:100|safe }}</p>

            	<p><a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-info">Read completely</a></p>
				<p><a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-info">Comments: {{ post.comments.count }}</a></p>
				</div>
		  </div>
        </div>
	{% endfor %}

<!--		&lt;!&ndash; Pagination &ndash;&gt;-->
<!--        <ul class="pagination justify-content-center mb-4">-->
<!--          <li class="page-item">-->
<!--            <a class="page-link" href="#">&larr; Older</a>-->
<!--          </li>-->
<!--          <li class="page-item disabled">-->
<!--            <a class="page-link" href="#">Newer &rarr;</a>-->
<!--          </li>-->
<!--        </ul>-->

		<div class="pages" align="center">
            <ul class="pagination justify-content-center mb-4">
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">Previous</a>
            {% endif %}

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">Next</a>
            {% endif %}
            </ul>
        </div>


{% endblock %}
        

blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="save btn btn-info">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_share.html
<!--{% extends "blog/base.html" %}-->

<!--{% load crispy_forms_tags %}-->

<!--{% block title %}Share a post{% endblock %}-->
<!--{% block content %}-->
<!--    {% if sent %}-->
<!--        <h1>E-mail successfully sent</h1>-->
<!--        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>-->
<!--    {% else %}-->
<!--        <h1>Share "{{ post.title }}" by e-mail</h1>-->
<!--        <form action="." method="post">-->
<!--            {{form|crispy}}-->
<!--            {% csrf_token %}-->
<!--            <input type="submit" value="Send e-mail">-->
<!--        </form>-->
<!--    {% endif %}-->
<!--{% endblock %}-->